Repository ChromeGaming/Squard-line, pull requests merged in 2024-06, with the labels that each got.

#105 Added git pull command in readme.md file
  README.md
  index.html
Labels: documentation, level1, gssoc

#108 Update README.md
  README.md
Labels: documentation, level1, gssoc

#93 Fixed social icons click while rotate animation
  index.html
Labels: enhancement, level1, gssoc

#125 Fixed a typo error in title of the website
  index.html
Labels: level1, gssoc

#130 Transform and Transition effect on Footer Social media section
  index.html
Labels: level1, gssoc

#137 Made the page responsive, Please review the code and approve
  Squard-line/LICENSE
  Squard-line/README.md
  Squard-line/desktop.ini
  Squard-line/favicon.ico
  Squard-line/game.js
  Squard-line/index.html
Labels: level2, gssoc

#143 Social media links open in new tab and changed the github link
  index.html
Labels: level1, gssoc

#84 added welcome animationn
  game.js
  index.html
  welcome.gif
Labels: enhancement, level2, gssoc

#98 undo and restart buttons
  game.js
  index.html
Labels: enhancement, level2, gssoc

#112 Added How to play? section
  index.html
Labels: enhancement, level2, gssoc

#115 Update README.md
  README.md
Labels: documentation, level1, gssoc

#124 Added Hover effect for footer and added some elements to footer
  game.js
  index.html
Labels: level1, gssoc

#148 Fixed mail icon
  index.html
Labels: bug, good first issue, level1, gssoc

#149 feat: 404 not found page added with config
  404.html
  404.png
Labels: level1, gssoc

#126 Rectified the issue of non-responsiveness in mobile version
  index.html
Labels: level2, gssoc

#158 Update CONTRIBUTING_GUIDELINE.md
  .github/CONTRIBUTING_GUIDELINE.md
Labels: level1, gssoc

#155 Modified to correct mail icon
  index.html
Labels: level1, gssoc

#153 Added light and dark theme toggling button
  index.html
Labels: level1, gssoc
