Repository ChromeGaming/Squard-line, pull requests merged in 2024-05, with the labels that each got.

#20 Ui_enhancement_and_introduction
  game.js
  index.html
Labels: enhancement, level2, gssoc

#36 Issue #23 Resolved :Add an favicon to the website
  index.html
Labels: enhancement, level1, gssoc

#40 [Bug] : Button accessable not Accessable
  game.js
Labels: level2, gssoc

#64 Improved text in Instructions/Functionary screen
  game.js
Labels: level1, gssoc

#79 added responsive footer
  index.html
Labels: level2, gssoc

#89 Dialogue Boxes instead of Alert
  game.js
  index.html
Labels: enhancement, level2, gssoc
